server:
  port: 8080

spring:
  application:
    name: cloud-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning_spring_cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*Dao.xml

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/